### ISSUE TITLE
Support for SPHINCS+

### ISSUE THREAD

**Issue by kamlesh0hrs** [smuellerDD/leancrypto#4]
Hi Stephan,

Are you planning to add support of SPHINCS+ to leancrypto ?
FIPS-205 (SLH-DSA) is now standardised and is a fallback solution if Lattice based algorithms are broken. It will be great if we can have support for SLH-DSA.

**Comment by smuellerDD** [comment]
Am Mittwoch, 21. August 2024, 10:09:05 MESZ schrieb kamlesh0hrs:

Hi kamlesh0hrs,

> Hi Stephan,
> 
> Are you planning to add support of SPHINCS+ to leancrypto ?
> FIPS-205 (SLH-DSA) is now standardised and is a fallback solution if Lattice
> based algorithms are broken. It will be great if we can have support for
> SLH-DSA.

For starters, leancrypto offers hybrid algos of Kyber and Dilithium where any 
potential issue with them should be caught.

Then I am not convinced that SPHINCS+ is truly helpful for a general-purpose 
signature mechanism as it is comparatively slow (granted, I did not perform my 
own measurements - so that statement is hear-say).

That said, SLH-DSA is certainly a viable option, but I would like to wait a 
bit (at least past the ICMC conference later in September) where I will be 
able to speak to the FIPS 203/4/5 authors about their state for the round 4 
candidates. I certainly want to add another signature schema, but I am not 
sure whether SLH-DSA should be the one.

With that in mind, I will certainly not want to implement Falcon with its 
floating point arithmetics. 

This means, I would like to keep the issue open until I have more information.

Ciao
Stephan

**Comment by kamlesh0hrs** [comment]
Makes sense ! Let's wait for ICMC.

Thanks,
Kamlesh

**Comment by smuellerDD** [comment]
BIKE KEM added

**Comment by smuellerDD** [comment]
SLH-DSA is coming after speaking to different folks. I have the heavy lifting for it including acceleration already implemented. After a bit of fine-tuning and Linux kernel support, the code will be pushed in the next days.

**Comment by kamlesh0hrs** [comment]
> SLH-DSA is coming after speaking to different folks. I have the heavy lifting for it including acceleration already implemented. After a bit of fine-tuning and Linux kernel support, the code will be pushed in the next days.

Thanks Stephan, that's great!

**Comment by smuellerDD** [comment]
SLH-DSA support merged.
